working on things

diff --git a/0vpn-options b/0vpn-options
--- a/0vpn-options
+++ b/0vpn-options
@@ -7,29 +7,33 @@ if [ "$0" == "$BASH_SOURCE" ]; then
     exit 1
 fi
 
-ZEROVPN_HUB_HOST="localhost"
-ZEROVPN_HUB_WIREGUARD_PORT="4242"
-ZEROVPN_HUB_SPOKE_ANNOUNCE_PORT="4243"
+ZEROVPN_SERVER_HOSTNAME="$(hostname --long)"
+ZEROVPN_SERVER_NAME="$(hostname --short)"
+ZEROVPN_WIREGUARD_PORT="4242"
+ZEROVPN_ANNOUNCE_PORT="4243"
+ZEROVPN_ANNOUNCE_INTERVAL="30"
 ZEROVPN_DNS_PORT="53"
 ZEROVPN_KEYFILE="key"
 ZEROVPN_TLD="internal"
 ZEROVPN_NETWORK="10.123.0.0/16"
 ZEROVPN_WIREGUARD_DEVICE="wg0"
-ZEROVPN_STATIC_SPOKES=""
-ZEROVPN_SPOKE_NAME="$(hostname)"
+ZEROVPN_STATIC_CLIENTS=""
+ZEROVPN_CLIENT_NAME="$(hostname --short)"
 
 function help {
     echo "Available options:"
-    echo "  --hub-host [hostname]            (default: \"$ZEROVPN_HUB_HOST\")"
-    echo "  --hub-wireguard-port [port]      (default: \"$ZEROVPN_HUB_WIREGUARD_PORT\")"
-    echo "  --hub-spoke-announce-port [port] (default: \"$ZEROVPN_HUB_SPOKE_ANNOUNCE_PORT\")"
+    echo "  --server-hostname [hostname]     (default: \"$ZEROVPN_SERVER_HOSTNAME\")"
+    echo "  --server-name [name]             (default: \"$ZEROVPN_SERVER_NAME\")"
+    echo "  --wireguard-port [port]          (default: \"$ZEROVPN_WIREGUARD_PORT\")"
+    echo "  --announce-port [port]           (default: \"$ZEROVPN_ANNOUNCE_PORT\")"
+    echo "  --announce-interval [seconds]    (default: \"$ZEROVPN_ANNOUNCE_INTERVAL\")"
     echo "  --dns-port [port]                (default: \"$ZEROVPN_DNS_PORT\")"
     echo "  --keyfile [filename]             (default: \"$ZEROVPN_KEYFILE\")"
     echo "  --tld [domain-name]              (default: \"$ZEROVPN_TLD\")"
     echo "  --network [network-spec]         (default: \"$ZEROVPN_NETWORK\")"
     echo "  --wireguard-device [device-name] (default: \"$ZEROVPN_WIREGUARD_DEVICE\")"
-    echo "  --static-spokes [list of names]  (default: \"$ZEROVPN_STATIC_SPOKES\")"
-    echo "  --spoke-name [name]              (default: \"$ZEROVPN_SPOKE_NAME\")"
+    echo "  --static-clients [list of names] (default: \"$ZEROVPN_STATIC_CLIENTS\")"
+    echo "  --client-name [name]             (default: \"$ZEROVPN_CLIENT_NAME\")"
 }
 
 while true; do
@@ -38,30 +42,36 @@ while true; do
     fi
 
     case $1 in
-        --hub-host) ZEROVPN_HUB_HOST="$2"; shift 2;;
-        --hub-wireguard-port) ZEROVPN_HUB_WIREGUARD_PORT="$2"; shift 2;;
-        --hub-spoke-announce-port) ZEROVPN_HUB_SPOKE_ANNOUNCE_PORT="$2"; shift 2;;
+        --server-hostname) ZEROVPN_SERVER_HOSTNAME="$2"; shift 2;;
+        --server-name) ZEROVPN_SERVER_NAME="$2"; shift 2;;
+        --wireguard-port) ZEROVPN_WIREGUARD_PORT="$2"; shift 2;;
+        --announce-port) ZEROVPN_ANNOUNCE_PORT="$2"; shift 2;;
+        --announce-interval) ZEROVPN_ANNOUNCE_INTERVAL="$2"; shift 2;;
         --dns-port) ZEROVPN_DNS_PORT="$2"; shift 2;;
         --keyfile) ZEROVPN_KEYFILE="$2"; shift 2;;
         --tld) ZEROVPN_TLD="$2"; shift 2;;
         --network) ZEROVPN_NETWORK="$2"; shift 2;;
         --wireguard-device) ZEROVPN_WIREGUARD_DEVICE="$2"; shift 2;;
-        --static-spokes) ZEROVPN_STATIC_SPOKES="$2"; shift 2;;
-        --spoke-name) ZEROVPN_SPOKE_NAME="$2"; shift 2;;
-        --help) help; shift 1; return 0;;
-        -h) help; shift 1; return 0;;
-        *) echo "Error parsing arguments. Expected argument. Got: \"$1\""; return 1;;
+        --static-clients) ZEROVPN_STATIC_CLIENTS="$2"; shift 2;;
+        --client-name) ZEROVPN_CLIENT_NAME="$2"; shift 2;;
+        --help) help; shift 1; exit 0;;
+        -h) help; shift 1; exit 0;;
+        *) echo "Error parsing arguments. Expected argument. Got: \"$1\""; exit 1;;
     esac
 done
 
-export ZEROVPN_HUB_HOST
-export ZEROVPN_HUB_WIREGUARD_PORT
-export ZEROVPN_HUB_SPOKE_ANNOUNCE_PORT
+export ZEROVPN_SERVER_HOSTNAME
+export ZEROVPN_SERVER_NAME
+export ZEROVPN_WIREGUARD_PORT
+export ZEROVPN_ANNOUNCE_PORT
+export ZEROVPN_ANNOUNCE_INTERVAL
 export ZEROVPN_DNS_PORT
 export ZEROVPN_KEYFILE
 export ZEROVPN_TLD
 export ZEROVPN_NETWORK
 export ZEROVPN_WIREGUARD_DEVICE
-export ZEROVPN_STATIC_SPOKES
-export ZEROVPN_SPOKE_NAME
+export ZEROVPN_STATIC_CLIENTS
+export ZEROVPN_CLIENT_NAME
 
+echo "Configuration:"
+for n in "${!ZEROVPN_@}"; do echo "  $n=${!n}"; done
